### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shakna-israel** [davebollinger/mt19937ar-lua#2]
> The MIT License (MIT)

> Copyright (c) 2016 David Bollinger (davebollinger at gmail dot com) ALL RIGHTS RESERVED

All rights reserved, means all rights reserved. That the rest of the rights in the license aren't granted.

So... Nobody can use this.

**Comment by davebollinger** [comment]
corrected.  it's an obsolete form, the default copyright already reserves all rights.  those specific rights that are explicitly granted by the license are (and were) still granted.  so with or without that phrase the net effect of the license hasn't changed.  thx
